@baseUrl = http://localhost:3000/api
@id = 351900e2-b443-41cf-945e-51906be7d96e

@auth_token = NmQzZDlhZGEtMjg0My00MmIyLWIyNjAtOTQ1MmEwOTcyNWI5Om1pcm9uZ2FAZW1haWwuY29t


###########################################################
# 👤 USERS


###
#CLIENTS
GET {{baseUrl}}/clients
Content-Type: application/json


###########################################################
# 🔹 Get all users
GET {{baseUrl}}/users
Accept: application/json


###
# 🔹 Create user (Register)
POST {{baseUrl}}/register
Content-Type: application/json
Accept: application/json

{
  "name": "Mironga",
  "email": "mironga@email.com",
  "password": "123456",
  "cpf": "123.456.789-00"
}


###
# 🔹 Delete user by ID
DELETE {{baseUrl}}/users?id={{id}}
Accept: application/json


###########################################################
# 🔐 AUTHENTICATION


###########################################################
# 🔹 Login
POST {{baseUrl}}/login
Content-Type: application/json
Accept: application/json

{
  "email": "mironga@email.com",
  "password": "123456"
}


###
# 🔹 Logout
POST {{baseUrl}}/logout
Accept: application/json


###########################################################
# 📅 RESERVATIONS


###########################################################


###
# 🔹 Get reservations by user ID (precisa de autenticação)
GET {{baseUrl}}/reservations
Accept: application/json
Cookie: auth_token={{auth_token}}


### 
# Create Reservation
POST {{baseUrl}}/reservations-products
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "user_id": "6d3d9ada-2843-42b2-b260-9452a09725b9",
  "client_id": "8ace3aa4-5f3a-4a64-bf0d-51103b0d9f23",
  "reservation_date": "2025-10-14T10:00:00.000Z",
  "status": "PENDING",
  "products": [
    {
      "id": "bacd098d-ccdc-42d6-9edd-30cc46b9b5ac",
      "quantity": 2
    }
  ]
}