@baseUrl = http://localhost:3000/api
@id = 351900e2-b443-41cf-945e-51906be7d96e

@auth_token = NmQzZDlhZGEtMjg0My00MmIyLWIyNjAtOTQ1MmEwOTcyNWI5Om1pcm9uZ2FAZW1haWwuY29t

###########################################################
# 👤 USERS
###########################################################

# 🔹 Get all users
GET {{baseUrl}}/users
Accept: application/json

###

# 🔹 Create user (Register)
POST {{baseUrl}}/register
Content-Type: application/json
Accept: application/json

{
  "name": "Mironga",
  "email": "mironga@email.com",
  "password": "123456",
  "cpf": "123.456.789-00"
}

###

# 🔹 Delete user by ID
DELETE {{baseUrl}}/users?id={{id}}
Accept: application/json


###########################################################
# 🔐 AUTHENTICATION
###########################################################

# 🔹 Login
POST {{baseUrl}}/login
Content-Type: application/json
Accept: application/json

{
  "email": "mironga@email.com",
  "password": "123456"
}

###

# 🔹 Logout
POST {{baseUrl}}/logout
Accept: application/json


# 🔹 Create reservation

POST {{baseUrl}}/reservations
Content-Type: application/json

{
  "user_id": "{{id}}",
  "client_id": "ID_DO_CLIENTE",
  "reservation_date": "2025-10-14T10:00:00.000Z",
  "status": "pending"
}


###########################################################
# 📅 RESERVATIONS
###########################################################

# 🔹 Get reservations by user ID (precisa de autenticação)
GET {{baseUrl}}/reservations
Accept: application/json
Cookie: auth_token={{auth_token}}

